
2022-06-02 16:04:07,751 INFO: errors [in F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\app.py:602]
2022-06-02 16:04:49,442 INFO: errors [in F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\app.py:600]
2022-06-02 16:06:07,184 INFO: errors [in F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\app.py:600]
2022-06-02 16:06:37,724 INFO: errors [in F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\app.py:600]
2022-06-02 16:09:19,964 INFO: errors [in F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\app.py:600]
2022-06-02 16:17:16,665 ERROR: Exception on /artists [GET] [in F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\util\_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x00000250C4DDE350 (otid=0x00000250C6E9CA40) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\app.py", line 333, in artists
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\util\_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\orm\session.py", line 4209, in __call__
    return self.class_(**local_kw)
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 137, in __init__
    track_modifications = app.config['SQLALCHEMY_TRACK_MODIFICATIONS']
KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'
2022-06-02 16:17:25,950 ERROR: Exception on /artists [GET] [in F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\util\_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x00000250C7F2EDA0 (otid=0x00000250C7F4E080) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\app.py", line 333, in artists
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 514, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\orm\scoping.py", line 47, in __call__
    sess = self.registry()
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\util\_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\sqlalchemy\orm\session.py", line 4209, in __call__
    return self.class_(**local_kw)
  File "F:\udacity\Project One\FSND\projects\01_fyyur\starter_code\env\lib\site-packages\flask_sqlalchemy\__init__.py", line 137, in __init__
    track_modifications = app.config['SQLALCHEMY_TRACK_MODIFICATIONS']
KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'
